# Generated by Django 3.0.6 on 2020-06-03 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_document', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_theme', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CleanText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_cleantext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_document', models.CharField(max_length=200)),
                ('path_file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_theme', models.CharField(max_length=200)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_material.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Relation_Theme_Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_material.AnalysisTheme')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_material.Theme')),
            ],
        ),
        migrations.CreateModel(
            name='Relation_Document_Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_material.AnalysisDocument')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_material.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_keyword', models.CharField(max_length=100)),
                ('periodicity_keyword', models.IntegerField(default=0)),
                ('cleantext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_material.CleanText')),
            ],
        ),
        migrations.AddField(
            model_name='cleantext',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_material.Theme'),
        ),
    ]
