# Generated by Django 3.0.6 on 2020-06-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='slug',
        ),
    ]
