# Generated by Django 3.0.6 on 2020-06-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name_document',
            field=models.CharField(max_length=200, verbose_name='Учебный материал'),
        ),
        migrations.AlterField(
            model_name='document',
            name='path_file',
            field=models.FileField(upload_to='documents/', verbose_name='Файл'),
        ),
    ]
